### ISSUE TITLE
Error received

### ISSUE THREAD

**Issue by jeremycherfas** [voxpelli/webpage-webmentions#208] opened 2024-06-12 09:59 UTC
Me again; sorry.

Zapier has been reporting an error for about 24 hours now.

```
Trigger partner failure: The app returned "500 Server Error: Internal Server Error for url: https://webmention.herokuapp.com/api/mentions?site=jeremycherfas.net&amp;format=html ; {&#34;error&#34;:&#34;An error occurred&#34;}".
```

I just checked manually, and the error persists.

Thanks

Jeremy

**Comment by voxpelli** [comment] 2024-06-12 10:15
Oh, I’ll check it out when I’m done with my haircut and have returned to the office 🙏

**Comment by voxpelli** [comment] 2024-06-13 09:13
Same error as last time, https://github.com/voxpelli/webpage-webmentions/issues/205#issuecomment-2098158868:

```
Error: Invalid URL, should be an absolute one (tag:indieweb.social:112569576381688668/,2013)
    at normalizeUrlRaw (/app/lib/utils/url-tools.js:28:11)
    at normalizeUrl (/app/lib/utils/url-tools.js:53:58)
    at /app/lib/classes/entries.js:88:36
    at Array.map (<anonymous>)
    at Entries._resolveDerivedData (/app/lib/classes/entries.js:88:25)
    at Entries._distillMention (/app/lib/classes/entries.js:117:15)
    at /app/lib/classes/entries.js:301:26
    at Array.map (<anonymous>)
    at /app/lib/classes/entries.js:301:10
```

**Comment by voxpelli** [comment] 2024-06-13 09:24
Note to self:

To list all interactions for a site:

```sql
SELECT entries.*
FROM entries
INNER JOIN mentions ON mentions.eid = entries.id
WHERE
  mentions.hostname = 'jeremycherfas.net' AND
  jsonb_path_exists(to_jsonb(entries.data), '$.interactions[*] ? (@ like_regex "^tag:")') = true
ORDER BY fetched DESC
LIMIT 100
```

Ultimately needs to be fixed in #206

**Comment by voxpelli** [comment] 2024-06-13 09:33
The three problematic mentions:

* http://brid.gy/comment/mastodon/@etp@indieweb.social/112569537544389674/112569592058970584/
* http://brid.gy/comment/mastodon/@etp@indieweb.social/112569537544389674/112569586071664150/
* http://brid.gy/comment/mastodon/@etp@indieweb.social/112569537544389674/112569576381688668/

**Comment by jeremycherfas** [comment] 2024-06-13 09:36
All of those give me a 404. I wonder whether there is a solution that could be implemented on brid.gy? Is it worth opening an issue there?

**Comment by voxpelli** [comment] 2024-06-13 09:37
These are the posts they match to:

* https://indieweb.social/@etp/112569592058970584
* https://secretbearsociety.org/@christof/112569586045945988
* https://mastodon.social/@InkySchwartz/112569576335811212

Probably the issue is the tag at: https://indieweb.social/@etp/112569537544389674

**Comment by voxpelli** [comment] 2024-06-13 09:39
The issue is that I save the tag interaction to a database column that the API layer later rejects when it tries to render the list. The API layer needs to not throw on such interactions or the the tag needs to be stripped when I consume it.

Its on me to handle any kind of unexpected data and not crash on it 😌

**Comment by voxpelli** [comment] 2024-06-13 09:40
That said, the above SQL query made it really easy to find and I have now manually purged the tag interactions, so your feed is back to working: https://webmention.herokuapp.com/api/mentions?site=jeremycherfas.net&format=html 🎉

**Closed as completed by voxpelli** 2024-06-13 09:40 UTC

**Comment by voxpelli** [comment] 2024-10-22 13:13
Ran this query now:

```sql
SELECT entries.*
FROM entries
WHERE
  jsonb_path_exists(to_jsonb(entries.data), '$.interactions[*] ? (@ like_regex "^tag:")') = true
ORDER BY fetched DESC
LIMIT 100
```

And updated the `entries.data` of each match to remove the `tag:` interactions. This to help fix: https://mastodon.social/@sil/113350927312769534

**Comment by jeremycherfas** [comment] 2024-11-28 07:47
Sorry; it is happening again.

```
Trigger partner failure: The app returned "500 Server Error: Internal Server Error for url: https://webmention.herokuapp.com/api/mentions?site=jeremycherfas.net&amp;format=html ; {&#34;error&#34;:&#34;An error occurred&#34;}".
```

**Comment by voxpelli** [comment] 2025-03-16 20:13
```sql
UPDATE
  entries
SET
  data = regexp_replace(entries.data::varchar, ',?"tag:[^"]+"', '', 'g')::json
WHERE
  jsonb_path_exists(to_jsonb(entries.data), '$.interactions[*] ? (@ like_regex "^tag:")') = true
```

Instead of manually editing, this `UPDATE` removes the failing mentions automatically
